;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		autopair-insert-opening
		autopair-skip-close-maybe
		beginning-of-buffer
		c-electric-delete-forward
		c-electric-semi&comma
		end-of-buffer
		))

(setq mc/cmds-to-run-once
      '(
		eval-print-last-sexp
		yas/expand
		))
