(deftheme moody "my custom theme")
(custom-theme-set-faces
 'moody
  '(default ((t (:foreground "#ffffff" :background "#040c16"))))
  '(cursor ((t (:background "#776c18"))))
  '(fringe ((t (:background "#030835"))))
  '(mode-line ((t (:foreground "#000000" :background "#73dd08"))))
  '(region ((t (:background "#1c4a26"))))
  '(font-lock-builtin-face ((t (:foreground "#328cec"))))
  '(font-lock-comment-face ((t (:foreground "#03d895"))))
  '(font-lock-function-name-face ((t (:foreground "#edd400"))))
  '(font-lock-keyword-face ((t (:foreground "#e52463"))))
  '(font-lock-string-face ((t (:foreground "#bf12ac"))))
  '(font-lock-type-face ((t (:foreground"#ff6b0a"))))
  '(font-lock-constant-face ((t (:foreground "#873612"))))
  '(font-lock-variable-name-face ((t (:foreground "#1ce105"))))
  '(minibuffer-prompt ((t (:foreground "#297fdb" :bold t))))
  '(font-lock-warning-face ((t (:foreground "red" :bold t))))
)
(provide-theme 'moody)
